greeting:
  message: "hello"
  name: "quarkus"
quarkus:
  http:
    port: 10000
    cors: true
    body:
      handle-file-uploads: true
      preallocate-body-buffer: true
    limits:
      max-body-size: 10G
  smallrye-openapi:
    path: "/swagger"
  swagger-ui:
    path: "/swagger-ui"

config:
  basePath: ${basePath}
  delimiter: "/"